name: Backend CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      
      - name: Build & Test with Maven
        run: mvn clean package -f backend/pom.xml

  dockerize-push:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build & Push Backend Image
        run: |
          docker build -t rdgmh/backend:latest ./backend
          docker push rdgmh/backend:latest

  deploy:
    needs: dockerize-push
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Terraform Apply (Backend)
        run: |
          cd infra/terraform
          terraform init
          terraform apply -auto-approve -target=azurerm_linux_web_app.backend
        env:
          TF_VAR_docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
          TF_VAR_docker_registry_password: ${{ secrets.DOCKERHUB_TOKEN }}