name: Backend Deployment

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: backend-${{ vars.PROJECT_NAME }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  IMAGE_NAME: backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Step 3: Set up Azure CLI
      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}", "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}", "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}", "tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      # Step 4: Configure App Service to use Docker image
      - name: Configure App Service to use Docker image
        run: |
          az webapp config container set \
            --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --docker-custom-image-name ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest \
            --docker-registry-server-url https://docker.io || exit 1

      # Step 5: Restart App Service (to apply changes)
      - name: Restart App Service (to apply changes)
        run: az webapp restart --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --name ${{ env.AZURE_WEBAPP_NAME }} || exit 1

      # Cleanup Steps
      # Step 6: Terminate Orphan Processes
      - name: Terminate Orphan Processes
        run: |
          pkill -f python || true
          pkill -f az || true

      # Step 7: Clear Azure CLI accounts
      - name: Clear Azure CLI accounts
        run: |
          set +e  # Temporarily disable error checking
          az account clear
          set -e  # Re-enable error checking

      # Step 8: Final Cleanup
      - name: Final Cleanup
        run: |
          # Ensure no lingering processes remain
          ps aux | grep -i 'python\|az' || true